# Generated by Django 6.1.1 on 2026-09-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
