# Generated by Django 6.1.1 on 2026-09-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_venta_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='concepto',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
