# Generated by Django 6.1.1 on 2026-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_venta_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='catalogo_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_desactualizado',
            field=models.BooleanField(default=False),
        ),
    ]
