# Generated by Django 6.1.1 on 2026-09-10 01:22

import apps.ticketing.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_venta_concepto'),
        ('tenancy', '0002_terminal_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha', models.DateField()),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('aforo', models.PositiveIntegerField(help_text='Capacidad del local para este evento, tomada de la habilitacion.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=16)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='tenancy.local')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('folio', models.CharField(max_length=24)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('usada', 'Usada'), ('anulada', 'Anulada')], default='emitida', max_length=16)),
                ('qr_token', models.CharField(default=apps.ticketing.models.generar_token, max_length=64, unique=True)),
                ('canal', models.CharField(choices=[('puerta', 'Puerta'), ('online', 'Online'), ('invitacion', 'Invitacion')], default='puerta', max_length=16)),
                ('comprador_nombre', models.CharField(blank=True, max_length=150)),
                ('comprador_contacto', models.CharField(blank=True, max_length=120)),
                ('usada_en', models.DateTimeField(blank=True, null=True)),
                ('anulada_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=250)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_anuladas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('usada_en_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_validadas', to='tenancy.terminal')),
                ('usada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas_validadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='sales.venta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='ticketing.evento')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoAforo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('ajuste', 'Ajuste')], max_length=16)),
                ('delta', models.IntegerField(help_text='Positivo suma gente adentro, negativo resta.')),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_aforo', to='ticketing.entrada')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_aforo', to='ticketing.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_aforo', to='tenancy.terminal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_aforo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de aforo',
                'verbose_name_plural': 'Movimientos de aforo',
                'ordering': ['-creado_en'],
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cupo', models.PositiveIntegerField(help_text='Cuantas entradas de este tipo se pueden vender.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='ticketing.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Tipo de entrada',
                'verbose_name_plural': 'Tipos de entrada',
                'ordering': ['evento', 'orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='ticketing.tipoentrada'),
        ),
        migrations.AddConstraint(
            model_name='evento',
            constraint=models.UniqueConstraint(fields=('tenant', 'local', 'fecha', 'nombre'), name='evento_unico_por_local_y_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientoaforo',
            index=models.Index(fields=['tenant', 'evento', '-creado_en'], name='ticketing_m_tenant__0c6262_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoaforo',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='aforo_delta_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='tipoentrada',
            constraint=models.UniqueConstraint(fields=('tenant', 'evento', 'nombre'), name='tipo_entrada_unico'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['tenant', 'evento', 'estado'], name='ticketing_e_tenant__1990f0_idx'),
        ),
        migrations.AddIndex(
            model_name='entrada',
            index=models.Index(fields=['tenant', 'qr_token'], name='ticketing_e_tenant__ed2445_idx'),
        ),
        migrations.AddConstraint(
            model_name='entrada',
            constraint=models.UniqueConstraint(fields=('tenant', 'evento', 'folio'), name='entrada_folio_unico'),
        ),
    ]
