# Generated by Django 6.1.1 on 2026-09-10 01:28

import apps.ticketing.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_terminal_deposito'),
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprador_nombre', models.CharField(blank=True, max_length=150)),
                ('comprador_contacto', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('confirmada', 'Confirmada'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='activa', max_length=16)),
                ('token', models.CharField(default=apps.ticketing.models.generar_token, max_length=64, unique=True)),
                ('expira_en', models.DateTimeField()),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=120)),
                ('medio_pago', models.CharField(blank=True, max_length=20)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('pago_tardio', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='ticketing.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='ticketing.tipoentrada')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['tenant', 'estado', 'expira_en'], name='ticketing_r_tenant__a07da8_idx'), models.Index(fields=['tenant', 'token'], name='ticketing_r_tenant__a6185f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
