# Generated by Django 6.1.1 on 2026-09-10 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='ticketing.reserva'),
        ),
    ]
