# Generated by Django 6.1.1 on 2026-09-10 01:33

import apps.ticketing.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_terminal_deposito'),
        ('ticketing', '0003_entrada_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('casa', 'Lista de la casa'), ('promotor', 'Lista de promotor'), ('dj', 'Lista del DJ'), ('sponsor', 'Sponsor'), ('staff', 'Staff'), ('cumpleanos', 'Cumpleanos')], default='casa', max_length=16)),
                ('cupo', models.PositiveIntegerField(help_text='Cuantas personas pueden entrar por esta lista en total.')),
                ('hora_de_corte', models.TimeField(blank=True, help_text='Despues de esta hora la lista no vale mas. Si es nulo, vale toda la noche.', null=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=16)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_creadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='ticketing.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ['evento', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ListaInvitado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('personas_que_cubre', models.PositiveSmallIntegerField(default=1, help_text='1 + acompanantes.')),
                ('qr_token', models.CharField(default=apps.ticketing.models.generar_token, max_length=64, unique=True)),
                ('anulado', models.BooleanField(default=False)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=250)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='ticketing.lista')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['lista', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('tipo_comision', models.CharField(choices=[('por_persona', 'Monto fijo por persona que ingresa')], default='por_persona', max_length=24)),
                ('valor_comision', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Promotor',
                'verbose_name_plural': 'Promotores',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='lista',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas', to='ticketing.promotor'),
        ),
        migrations.CreateModel(
            name='ComisionPromotor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personas', models.PositiveIntegerField(default=0, help_text='Personas que ingresaron.')),
                ('base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('estado', models.CharField(choices=[('calculada', 'Calculada'), ('aprobada', 'Aprobada'), ('pagada', 'Pagada')], default='calculada', max_length=16)),
                ('pagada_en', models.DateTimeField(blank=True, null=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='ticketing.evento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to='ticketing.promotor')),
            ],
            options={
                'verbose_name': 'Comision de promotor',
                'verbose_name_plural': 'Comisiones de promotores',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UsoLista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('personas', models.PositiveSmallIntegerField(default=1)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='ticketing.listainvitado')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='ticketing.lista')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_de_lista', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_de_lista', to='tenancy.terminal')),
            ],
            options={
                'verbose_name': 'Uso de lista',
                'verbose_name_plural': 'Usos de lista',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='listainvitado',
            index=models.Index(fields=['tenant', 'qr_token'], name='ticketing_l_tenant__ae994b_idx'),
        ),
        migrations.AddConstraint(
            model_name='listainvitado',
            constraint=models.UniqueConstraint(fields=('tenant', 'lista', 'nombre'), name='invitado_unico_por_lista'),
        ),
        migrations.AddConstraint(
            model_name='promotor',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='promotor_nombre_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='lista',
            constraint=models.UniqueConstraint(fields=('tenant', 'evento', 'nombre'), name='lista_unica_por_evento'),
        ),
        migrations.AddConstraint(
            model_name='comisionpromotor',
            constraint=models.UniqueConstraint(fields=('tenant', 'evento', 'promotor'), name='comision_unica_por_evento_y_promotor'),
        ),
    ]
