# Generated by Django 6.1.1 on 2026-09-10 01:07

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre comercial')),
                ('slug', models.SlugField(help_text='Se usa para resolver el tenant por subdominio.', max_length=63, unique=True, verbose_name='Subdominio')),
                ('rut', models.CharField(blank=True, max_length=20, verbose_name='RUT')),
                ('plan', models.CharField(choices=[('base', 'Base'), ('acceso', 'Acceso'), ('completo', 'Completo')], default='base', max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Boliche',
                'verbose_name_plural': 'Boliches',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('aforo', models.PositiveIntegerField(blank=True, null=True)),
                ('zona_horaria', models.CharField(default='America/Montevideo', max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('barra', 'Barra'), ('puerta', 'Puerta'), ('caja', 'Caja'), ('admin', 'Administracion')], max_length=20)),
                ('identificador', models.CharField(blank=True, max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminales', to='tenancy.local')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'ordering': ['local__nombre', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='local',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='local_nombre_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='terminal',
            constraint=models.UniqueConstraint(fields=('tenant', 'local', 'nombre'), name='terminal_nombre_unico_por_local'),
        ),
    ]
