# Generated by Django 6.1.1 on 2026-09-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_terminal_deposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='catalogo_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
