# Generated by Django 6.1.1 on 2026-09-10 01:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_principal', models.BooleanField(default=False, help_text='El deposito central del local.')),
                ('activo', models.BooleanField(default=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='tenancy.local')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Deposito',
                'verbose_name_plural': 'Depositos',
                'ordering': ['local__nombre', 'nombre'],
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=16)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.deposito')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalog.insumo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Saldo de stock',
                'verbose_name_plural': 'Saldos de stock',
                'ordering': ['deposito__nombre', 'insumo__nombre'],
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('traslado_entrada', 'Traslado (entrada)'), ('traslado_salida', 'Traslado (salida)'), ('merma', 'Merma o rotura'), ('consumo_interno', 'Consumo interno'), ('ajuste', 'Ajuste'), ('inventario', 'Conteo de inventario')], max_length=24)),
                ('cantidad', models.DecimalField(decimal_places=4, help_text='Con signo, en unidad base.', max_digits=16)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('motivo', models.CharField(blank=True, max_length=250)),
                ('referencia_tipo', models.CharField(blank=True, max_length=60)),
                ('referencia_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=80)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='stock.deposito')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='catalog.insumo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to='tenancy.terminal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de stock',
                'verbose_name_plural': 'Movimientos de stock',
                'ordering': ['-creado_en'],
                'base_manager_name': 'unscoped',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='deposito',
            constraint=models.UniqueConstraint(fields=('tenant', 'local', 'nombre'), name='deposito_unico_por_local'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'deposito', 'insumo'), name='stock_item_unico'),
        ),
        migrations.AddIndex(
            model_name='stockmovimiento',
            index=models.Index(fields=['tenant', '-creado_en'], name='stock_stock_tenant__af0815_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovimiento',
            index=models.Index(fields=['tenant', 'deposito', 'insumo'], name='stock_stock_tenant__cfc3e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='movimiento_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='stockmovimiento',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='movimiento_cantidad_no_cero'),
        ),
    ]
