# Generated by Django 6.1.1 on 2026-09-10 01:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sales', '0002_alter_venta_idempotency_key'),
        ('stock', '0002_alter_stockmovimiento_idempotency_key'),
        ('tenancy', '0002_terminal_deposito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=16)),
                ('ciego', models.BooleanField(default=True, help_text='Si es ciego, el teorico se revela recien al cerrar.')),
                ('iniciado_en', models.DateTimeField()),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('duracion_seg', models.PositiveIntegerField(blank=True, help_text='Cuanto tardo el conteo, medido por el sistema.', null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='stock.deposito')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('turno', models.ForeignKey(blank=True, help_text='La noche a la que se atribuye la varianza.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to='sales.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteo',
                'verbose_name_plural': 'Conteos',
                'ordering': ['-iniciado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ConteoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('unidades_cerradas', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('fraccion_abierta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4)),
                ('cantidad_declarada', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('cantidad_teorica', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.conteo')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conteo_items', to='catalog.insumo')),
                ('presentacion', models.ForeignKey(blank=True, help_text='Botella, caja... Si es nulo, se cuenta en la unidad base.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conteo_items', to='catalog.insumopresentacion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Item de conteo',
                'verbose_name_plural': 'Items de conteo',
                'ordering': ['conteo', 'insumo__nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('diferencia', models.DecimalField(decimal_places=4, max_digits=16)),
                ('motivo', models.CharField(max_length=250)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_autorizados', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='stock.stockmovimiento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('conteo_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ajuste', to='stock.conteoitem')),
            ],
            options={
                'verbose_name': 'Ajuste de inventario',
                'verbose_name_plural': 'Ajustes de inventario',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='conteo',
            index=models.Index(fields=['tenant', '-iniciado_en'], name='stock_conte_tenant__7ea991_idx'),
        ),
        migrations.AddConstraint(
            model_name='conteoitem',
            constraint=models.UniqueConstraint(fields=('conteo', 'insumo'), name='conteo_item_unico_por_insumo'),
        ),
    ]
