# Generated by Django 6.1.1 on 2026-09-10 01:55

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_tenant_catalogo_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialDePago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('simulado', 'Simulado (desarrollo)')], default='mercadopago', max_length=24)),
                ('access_token', models.CharField(blank=True, max_length=250)),
                ('external_pos_id', models.CharField(blank=True, max_length=64)),
                ('clave_de_firma', models.CharField(blank=True, max_length=250)),
                ('activo', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Credencial de pago',
                'verbose_name_plural': 'Credenciales de pago',
                'ordering': ['tenant', 'proveedor'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'proveedor'), name='credencial_unica_por_proveedor')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
