# Generated by Django 6.1.1 on 2026-09-10 01:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=16, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('magnitud', models.CharField(choices=[('volumen', 'Volumen'), ('masa', 'Masa'), ('unidad', 'Unidad')], max_length=16)),
                ('factor_a_base', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['magnitud', 'factor_a_base', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Categoria de producto',
                'verbose_name_plural': 'Categorias de producto',
                'ordering': ['orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('costo_promedio', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('codigo_barras', models.CharField(blank=True, max_length=64)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('unidad_base', models.ForeignKey(help_text='Unidad en la que se lleva el stock de este insumo.', on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='catalog.unidadmedida')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InsumoPresentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Botella, caja, fardo...', max_length=100)),
                ('factor_a_unidad_base', models.DecimalField(decimal_places=4, help_text='Cuantas unidades base entran. Botella de 750 ml = 750 si la base es ml.', max_digits=14)),
                ('codigo_barras', models.CharField(blank=True, max_length=64)),
                ('es_compra', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='catalog.insumo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['insumo__nombre', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_iva', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5)),
                ('es_combo', models.BooleanField(default=False, help_text='Si es combo, descuenta stock via sus productos hijos.')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalog.categoriaproducto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='catalog.producto')),
                ('producto_hijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_combos', to='catalog.producto')),
            ],
            options={
                'verbose_name': 'Item de combo',
                'verbose_name_plural': 'Items de combo',
                'ordering': ['combo__nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activa', models.BooleanField(default=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='catalog.producto')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecetaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('merma_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Porcentaje que se suma por derrame o descarte.', max_digits=5)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receta_items', to='catalog.insumo')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.receta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.tenant', verbose_name='Boliche')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receta_items', to='catalog.unidadmedida')),
            ],
            options={
                'verbose_name': 'Item de receta',
                'verbose_name_plural': 'Items de receta',
                'ordering': ['receta__producto__nombre', 'insumo__nombre'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='categoriaproducto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='categoria_nombre_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='insumopresentacion',
            constraint=models.UniqueConstraint(fields=('tenant', 'insumo', 'nombre'), name='presentacion_unica_por_insumo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='producto_nombre_unico_por_tenant'),
        ),
        migrations.AddConstraint(
            model_name='comboitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'combo', 'producto_hijo'), name='combo_item_unico'),
        ),
        migrations.AddConstraint(
            model_name='insumo',
            constraint=models.UniqueConstraint(fields=('tenant', 'nombre'), name='insumo_nombre_unico_por_tenant'),
        ),
    ]
